using System;
using UnityEngine;   // Vector3 (the shared `position` field)

namespace Haf.Schema
{
    // THE shared model schema — the fields stored IDENTICALLY (type + name + default) by the editor's ModelDef
    // and the plugin's ModelEntry. Defined ONCE here; both inherit it, so a field can't drift between them and
    // the ~64 duplicated declarations collapse to one. GUID (int[] vs sa/sb/..), bake-only, and runtime-state
    // fields are NOT here (they differ by design) — the parity guard still covers those. netstandard2.0, no deps.
    [Serializable]
    public class HafModelSchema
    {
        public string resourceName = "";
        public string pawnDescription = "";
        public Vector3 position;               // position offset (z = waterline); static: baked into the mesh, animated: applied at runtime
        public float scale = 1f;            // RUNTIME multiplier on the pawn's ObjectSpace.Scale (Resize Lab; no re-bake). The plugin already parsed this config-only field — now surfaced. 1 = unchanged.
        public string hideMeshes = "";      // RUNTIME (not baked): comma-separated donor-FRAGMENT name substrings the plugin hides on this unit — e.g. hide a fragment-based extra. NOTE: a donor's animated skinned sub-parts (a helicopter rotor, spinning wheels) are encoded at pawn-spawn and CANNOT be hidden this late — choose a donor without such parts. Find fragment names in the BepInEx log: "[Uni] <name> donor fragment[i] mesh='...'".
        public bool animStateDriven = false; // ANIMATED only (Phase 2, 2026-07-19): STATE-DRIVEN mode — the unit plays the IDLE clip (animClip) when standing, the MOVEMENT clip (animClipMove) while moving, and optionally the AFTER-MOVEMENT clip (animClipAfter) once on stopping. Mutually exclusive with the single-clip behaviors (fireOnAttack/deployOnStop) — a model is EITHER a single always-loop/behavior clip OR state-driven. Off = today's single-clip path, so old registries are byte-identical.
        public bool disabled = false;       // DEBUG (RUNTIME-ONLY): skip this override entirely so the ORIGINAL vanilla unit renders — to compare against the custom model or observe the donor's own animation. Save (no bake) + relaunch.
        public bool clearAimLayer = false;  // RUNTIME-ONLY: clear the game's procedural BoneRotation layer for this model (artillery — the donor streams aim/wheel junk that twists the rig). Needed by STATE-DRIVEN artillery (the legacy fire/deploy rule cleared it implicitly); characters must leave it OFF (it carries their facing).
        public string turretBone = "";      // RUNTIME-ONLY (TURRETIZE): bone-name SUBSTRING (renamed b###_<orig>) of a turret to aim at the target. The plugin retargets the game's aim/heading angle onto this bone so the turret tracks the enemy. "" = no turret aim. No re-bake — set it, Save (no bake), relaunch.
        public int turretAxis = -1;         // RUNTIME-ONLY: aim-axis override for the turret bone. -1 = keep the game's axis (reads as PITCH on most bones); 0/1/2 = force local X/Y/Z. A vehicle turret wants its YAW axis; a mechanized artillery barrel wants its PITCH axis. Dial 0/1/2 to find it — Save (no bake) + relaunch, no rebuild.
        public string muzzleOffset = "";    // RUNTIME-ONLY dial: "x,y,z" WORLD-units added to the pinned fire origin (flash + tracer start) — the empirical fix when the gun bone's head sits at the model base (the Ehrhardt). Save (no bake) + relaunch to dial. "" = none.
        public string muzzleBone = "";      // RUNTIME-ONLY (MUZZLE-RELOCATE): bone-name SUBSTRING (renamed b###_<orig>) the weapon muzzle-flash fires FROM. The donor's fire clip names ITS own weapon socket (an AA gun's "Canon"), absent on our renamed rig, so the flash lands off-side; the plugin redirects the lookup to THIS bone (e.g. the turret/gun) so the flash anchors on our unit. "" = leave vanilla. No re-bake — set it, Save (no bake), relaunch.
        public int attackRepeats = 1;       // STATE-DRIVEN only: how many times the ATTACK clip replays per trigger (window = repeats × clip duration). For short recoil-pop clips (shootAR2s = 0.17s). RUNTIME-ONLY — Save (no bake) is enough.
        public string handPropName = "";    // HAND PROP: the Prop Lab resource name of a weapon glued to a bone of OUR skeleton (assets <name>_Collection / <name>_DistrictMesh). RUNTIME-ONLY.
        public string handPropGuid = "";    // HAND PROP: the <name>_Collection Amplitude guid "a,b,c,d" (printed + clipboarded by the Prop Lab bake). "" = no hand prop.
        public string handPropMat = "";     // HAND PROP: borrowed material guid "a,b,c,d"; "" = the shared EQ_DLC04_Weapons material (sling-verified).
        public string handPropBone = "";    // HAND PROP: bone-name SUBSTRING on our skeleton (bones are renamed b###_<orig>); "" = "R_Hand".
        public string handPropAngles = "";  // HAND PROP: draw-time rotation "x,y,z" (deg) — stamped onto the collection's FxMeshContent.ImportAngles at runtime (the only angles the fragment path reads). "" = the baked value. RUNTIME-ONLY: change + Save (no bake) + relaunch.
        public float idleAltInterval = 25f; // RUNTIME (not baked): avg SECONDS between idle-alt one-shots, jittered 0.6-1.4x (like the idle growl's cadence). <=0 disables. One performer per unit type per firing (packmates keep idling).
        public float animPhaseSpread = 0.5f; // RUNTIME (not baked): spread the LOOPING animation across a unit's pawns so they don't all move in lockstep (12 canoes rocking as one rigid raft; 8 monsters swinging their heads in unison). DEFAULT 0.5 = half the clip — desynchronises convincingly while the unit still reads as one group; 1 = the whole clip, 0 = lockstep (the pre-2026-07-31 behaviour). Each pawn keeps its phase across LOD rebuilds (tracked by position), so zoom can't reset it. One-shots (attack/deploy/fire) are timed from their trigger and never shifted.
        public bool respawnAfterLoad = false; // RUNTIME (not baked): fix the save-load first-instance rotor race. The engine draws the FIRST custom pawn that borrows a donor's animated sub-part (a helicopter rotor) built during a save-load ~1 low; anything rebuilt AFTER load is correct. Tick this and the plugin re-runs the game's own PresentationUnit.UpdatePawns (release+re-instantiate) on this model's units ~3s post-load, clearing it. Set ONLY for borrowed-rotor models; a brief one-time flicker as those units rebuild.
        public bool freezeDonorAnim = false;  // RUNTIME (not baked): freeze the DONOR's idle/move animation so a STATIC borrowed mesh doesn't inherit its pose bob. Use when your model rides a donor whose hover/idle wiggle looks wrong on it (e.g. the Zeppelin on the Recon-Drone donor). The plugin pins every pawn pose's Time to 0 each frame, holding the mesh rigid while it still glides tile-to-tile. Static models only (animated models play their own baked clip); no re-bake.
        public bool fireOnAttack = false;   // RUNTIME (not baked): ANIMATED only. Play the baked clip ONCE when this unit attacks (bombards) instead of looping — the barrel rests, then elevates on the shot and returns. The plugin listens for SimulationEvent_ArtilleryStrikeStarted, matches the firing unit to this entry, and plays a single 0->1 pass of the clip (author it to start AND end at rest). Leave off for a continuously-looping clip (a drone's spinning prop).
        public bool deployOnStop = false;   // RUNTIME (not baked): ANIMATED only. Hold the baked clip's DEPLOYED pose when the unit is idle, and snap to the UNDEPLOYED pose (frame 0) while it moves — e.g. a howitzer whose barrel/trails deploy when it stops and fold for travel. Author the clip so frame 0 = travelling (undeployed) and deployPoseTime = deployed. Per-unit, instant snap, no state machine. Combine with fireOnAttack for deploy+recoil on one clip: author deploy in [0, deployPoseTime] and the recoil kickback in [deployPoseTime, 1] (deploy_convert.py recoilSrcStart/End); the fire event then sweeps the tail once.
        public float deployPoseTime = 1f;   // RUNTIME (not baked): deployOnStop only. Normalized clip time (0..1) of the DEPLOYED pose held when idle. 1 = a purpose-made deploy clip's end. (0.5 was used to prove the mechanism with the barrel-fire clip's raised plateau.)
        public float deploySpeed = 1f;      // RUNTIME (not baked): deployOnStop only. Speed multiplier on the gradual deploy-on-stop ramp (1 = the clip's authored speed, 2 = twice as fast). Folding on move is always instant, so this only affects the forward deploy.
        public float recoilSpeed = 1f;      // RUNTIME (not baked): deployOnStop + fireOnAttack. Speed multiplier on the recoil-on-fire kickback (1 = the tail's authored speed, 3 = the kick plays 3x faster). Tune this if the kick reads too slow/fast.
        public float brightness = 1f;       // RUNTIME (not baked): UNIVERSAL skin brightness GAMMA (1 = unchanged, >1 lighter, <1 darker), applied BEFORE desaturate/tint. Multiplicative in the dark range with pinned endpoints, so a dark atlas actually lightens without washing out — the additive tint tops out (+30 lifts 18 to only 48). Managed by the Unit Retexture window.
        public float desaturate = 0f;       // RUNTIME (not baked): TEXTURE-ONLY GREY variant. 0 = off. >0 = don't repoint the mesh; isolate this unit's output layer and paint a DESATURATED copy of its OWN atlas (1 = full grey) + neutralise the civ-colour tint. Makes a Common copy read as a bland grey version of an emblematic unit (they share the layer, so the original is untouched). No bake / no custom model needed — a hand-added or window-added registry entry keyed on the copy's pawnDescription.
        public float tintR = 0f;            // RUNTIME (not baked): UNIVERSAL skin colour offset, red (-255..+255, 0 = none). Added AFTER desaturate to whatever skin the unit gets (its own atlas OR the textureFile PNG). Equal negatives on R/G/B = darken, positives = brighten, one channel tints. Managed by the Unit Retexture window.
        public float tintG = 0f;            // RUNTIME (not baked): universal skin colour offset, green (-255..+255).
        public float tintB = 0f;            // RUNTIME (not baked): universal skin colour offset, blue (-255..+255).
        public string textureFile = "";     // RUNTIME (not baked): TEXTURE-ONLY RETEXTURE. A PNG filename in the game's BepInEx/config/haf_skins/. When set, the plugin hot-loads that PNG onto the unit's ISOLATED output layer (vanilla mesh kept, original untouched) — no bake/rebuild. Takes precedence over desaturate. Managed by the Unit Retexture window (Tools ▸ ENC ▸ Unit Retexture): paint on a dump of the unit's own atlas, drop it in haf_skins/.
        public bool silenceDonorVfx = false; // RUNTIME (not baked): SUPPRESS the donor's MecanimEvent VFX (muzzle flashes, animator smoke) on this unit — those effects anchor to DONOR bone names that don't exist on the injected skeleton, so they render misplaced (the AA-gun's floating flash). VFX ONLY: donor sounds are untouched (that's silenceDonorAudio). Factory checkbox "Silence donor VFX (flashes)".
        public bool useDonorClip = false;   // RUNTIME (not baked): keep the DONOR's own animation clip driving our injected skeleton (skip the clip swap). The donor's channels map to our bones BY INDEX, so this only reads correctly on a rig built to donor convention: same bone count/order (armature, body, main rotor, tail rotor) and identity rests — the plugin rebases our root to identity at injection. Proven on the StealthHelicopter: full helicopter flight motion (body bob + rotor spin) from the Cobra donor clip on our own mesh. Factory checkbox "Use donor animation clip".
        public float hugDrop = 0f;          // RUNTIME (not baked): TERRAIN HUG, degrees of "fly lower" in world units (NEGATIVE, e.g. -2; 0 = off). The engine already flies air units at a terrain-relative altitude, but that ignores BUILDINGS — which is why an aircraft needs a Position Z lift to clear a city skyline. This subtracts that lift again wherever no BUILT district (Extension_*; cultivated Exploitation/Ruin tiles don't count) sits under or ahead of the unit, so it skims low over open country and climbs only for the city. Eased, and the probe leads along the movement vector so it climbs BEFORE the buildings. Factory field "Terrain hug — drop".
        public float hugLookahead = 1.5f;   // RUNTIME (not baked): TERRAIN HUG, how far AHEAD of the unit the district probe sits, in world units. Bigger = starts climbing earlier (more anticipation, like a pilot); 0 = purely reactive. Only meaningful with hugDrop != 0.
        public float turnRate = 0f;         // RUNTIME (not baked): TURN EASE, degrees/second the model turns toward a new heading (0 = off = the engine's instant facing SNAP on a move order). 180 = a 90-degree turn takes half a second. Every angle eases, 180s included; teleports/battle placement still snap. Factory field "Turn ease — rate".
        public float turnBank = 0f;         // RUNTIME (not baked): TURN EASE, maximum roll INTO the turn, degrees (0 = no bank; negative flips the lean). Aircraft read best with a few degrees; ground/naval units usually want 0. Only meaningful with turnRate > 0.
        public bool silenceDonorAudio = false; // RUNTIME (not baked): SUPPRESS all of the borrowed donor's Wwise sound on this unit's pawns. A custom creature that reuses a donor (e.g. the Abomination borrows a BEAR) inherits the donor's IDLE growl and combat MAUL/SCRATCH — they ride in on the reused animator/pawn-description, not on any nullable data field. The plugin drops every AudioEmitter.PostEvent on our opted-in pawns (the one chokepoint both sounds use) and StopAll's the idle loop once. Only silences Wwise; our own custom WAVs (soundFile etc., Unity AudioSource) still play, so it composes with a replacement sound. Reusable on any unit with an unwanted inherited sound.
        public bool engineSound = false;    // RUNTIME (not baked): fire the per-ship engine MOVE sound (Play_UNIT_Vehicles_<Type>_Start/_Stop) on this unit's instances. Our injected/retextured units never trigger it themselves (it rides the audio-service path tied to the vanilla unit's move state), so they're silent on move. The plugin detects each instance's move-start/stop (render-position delta) and posts the engine event onto the pawn's AudioEmitter. Naval units proven; land/air TBD.
        public bool hideSubPawns = false;   // RUNTIME (not baked): duplicate-pawn suppression for squadron-class donors (gunships spawn 4-5 pawns via the air hardcode): keeps the first pawn per frame, hides+buries the rest. Also gates the plugin's ghost-hunt diagnostics. Leave OFF for units that WANT the multi-pawn squadron look.
        public float moveTilt = 0f;         // RUNTIME (not baked): degrees of nose-down pitch while the unit MOVES (helicopter forward-flight attitude), eased in/out. 0 = off. Negative if the model's pitch axis reads inverted.
        public string engineStartEvent = ""; // RUNTIME (not baked): Wwise event NAME posted on move-START (e.g. Play_UNIT_Vehicles_StealthCorvette_Start). Set => posted BY NAME so it works for the FIRST unit at load (no live capture). Empty => the plugin falls back to a handle auto-captured from any same-family vehicle that moved this session. Extract names via the F8 "Dump Sound Catalog" (writes haf_sound_catalog.txt).
        public string engineStopEvent = "";  // RUNTIME (not baked): Wwise event name posted on move-STOP (..._Stop).
        public string soundFile = "";        // RUNTIME (not baked): CUSTOM audio, LOOP — a WAV filename in the game's BepInEx/config/haf_sounds/. The plugin loads it (Unity AudioSource, not Wwise) and plays it as a LOOPING 3D sound WHILE the unit moves — for units the game has no sound for (drones, zeppelins) or a bespoke engine. Convert mp3/ogg to WAV first (16-bit PCM). Managed by the Unit Retexture window.
        public string soundStartFile = "";   // RUNTIME (not baked): CUSTOM audio one-shot played on move-START (spool-up) — a WAV in haf_sounds/.
        public string soundStopFile = "";    // RUNTIME (not baked): CUSTOM audio one-shot played on move-STOP (spool-down) — a WAV in haf_sounds/.
        public float soundVolume = 1f;       // RUNTIME (not baked): travel-loop volume (0..2).
        public float soundStartVolume = 1f;  // RUNTIME (not baked): move-start one-shot volume (0..2).
        public float soundStopVolume = 1f;   // RUNTIME (not baked): move-stop one-shot volume (0..2).
        public string soundIdleFile = "";    // RUNTIME (not baked): CUSTOM audio one-shot growl played OCCASIONALLY WHILE IDLE (unit not moving) — a WAV in haf_sounds/. Replaces a donor's periodic idle vocalization (pair with silenceDonorAudio). The plugin fires it on a randomized per-pawn timer (see soundIdleInterval). Managed by the Unit Sound window.
        public float soundIdleVolume = 1f;   // RUNTIME (not baked): idle-growl one-shot volume (0..2).
        public float soundIdleInterval = 11f; // RUNTIME (not baked): AVERAGE seconds between idle growls, jittered 0.6..1.4x per pawn so a pack doesn't chorus. <=0 disables.
        public float soundIdleGroupRadius = 10f; // RUNTIME (not baked): GROUP de-dup radius. A unit is many pawns; without this every pawn of a formation growls at once (a "cut-up" wall). Growls within this radius of another recent growl are suppressed, so a clustered unit snarls with ONE voice per interval. <=0 = per-pawn (no de-dup).
        public string soundAttackFile = "";  // RUNTIME (not baked): CUSTOM one-shot played ON ATTACK (each swing/shot) — a WAV in haf_sounds/. A DISTINCT, more VIOLENT sound than the idle growl; the plugin fires it from the attack hook with a per-pawn min-gap so rapid multi-swing fights don't machine-gun it.
        public float soundAttackVolume = 1f; // RUNTIME (not baked): attack one-shot volume (0..2).
        public float soundAttackOffset = 0f; // RUNTIME (not baked): seconds INTO the attack WAV where playback starts — skip a silent/windup lead-in so the impact lands on the swing. 0 = from the top.
        public string soundDeathFile = "";   // RUNTIME (not baked): CUSTOM one-shot when a pawn of this unit DIES (rattle/scream) — a WAV in haf_sounds/. Per-entry min-gap so a wiped stack doesn't chorus.
        public float soundDeathVolume = 1f;  // RUNTIME (not baked): death one-shot volume (0..2).
        public float soundDeathOffset = 0f;  // RUNTIME (not baked): seconds into the death WAV (same semantics as the attack offset).
        public string soundBattleFile = "";  // RUNTIME (not baked): CUSTOM WAR CRY one-shot when a battle STARTS with this unit in it — camera-anchored, one cry per battle.
        public float soundBattleVolume = 1f; // RUNTIME (not baked): war-cry volume (0..2).
        public float soundBattleOffset = 0f; // RUNTIME (not baked): seconds into the war-cry WAV.
        public float gunElevMax;            // RUNTIME-ONLY (GUN ELEVATION): max barrel raise (deg) during a bombard, proportional to target distance. 0 = off.
        public int gunElevAxis;             // RUNTIME-ONLY: the gun bone's local PITCH axis for the elevation (0=X, 1=Y, 2=Z).
    }
}
