#!/usr/bin/env bash
# Sync the GitHub wiki from the repo docs (the wiki pages' header has referenced this script since the
# first sync — this is now actually it). Usage:
#   git clone https://github.com/sswelm/HumankindAssetFramework.wiki.git <dir>
#   tools/sync_wiki.sh <dir>     # then commit+push inside <dir>
# Mapping: docs/README.md -> Home, repo README.md -> Overview, CHANGELOG.md -> Changelog, docs/X.md -> X,
#          docs/notes/X.md -> X  (the wiki page namespace is FLAT — see the collision guard below).
# Links: page links become flat wiki page names; directory landing pages get explicit destinations; repo-only files
#        remain GitHub links. The sidebar is tracked in tools/wiki-sidebar.md and copied on every sync.
set -euo pipefail
cd "$(dirname "$0")/.."
WIKI="${1:?usage: tools/sync_wiki.sh <wiki-clone-dir>}"
# GUARDS (2026-08-20): a relative <dir> (".") used to resolve against the repo root after the cd above — and on a
# case-insensitive filesystem the emitted Changelog.md then OVERWROTE the repo's CHANGELOG.md and strewed 42 wiki
# pages through the repo root. The destination must be an existing wiki clone OUTSIDE this repo.
WIKI="$(cd "$WIKI" 2>/dev/null && pwd)" || { echo "FAIL: wiki dir does not exist: $1" >&2; exit 1; }
REPO_ROOT="$(pwd)"
case "$WIKI/" in "$REPO_ROOT"/*) echo "FAIL: wiki dir resolves inside the repo ($WIKI) — pass the wiki CLONE dir" >&2; exit 1;; esac
[ -d "$WIKI/.git" ] || { echo "FAIL: $WIKI is not a git clone (no .git) — clone the wiki repo there first" >&2; exit 1; }

# COLLISION GUARD (2026-08-20, added with the docs/notes/ archive split): the wiki namespace is flat, so
# docs/Foo.md and docs/notes/Foo.md would emit the SAME page and one would silently overwrite the other.
# Fail loudly instead — rename one of the two source files.
dupes="$(for f in docs/*.md docs/notes/*.md; do basename "$f"; done | sort | uniq -d || true)"
[ -z "$dupes" ] || { echo "FAIL: duplicate basename(s) across docs/ and docs/notes/ — the wiki namespace is flat:" >&2
                     printf '  %s\n' $dupes >&2; exit 1; }

HDR='> _Auto-generated from the repo docs by `tools/sync_wiki.sh` — edit the source Markdown in the repo, not this wiki page._'
REPO='https://github.com/sswelm/HumankindAssetFramework'   # repo-only files (CREDITS/LICENSE/llms.txt/examples) can't be wiki pages

# Remove only pages generated by an earlier run. This deletes stale pages after a source rename/removal while
# preserving hand-authored wiki pages that do not carry the generator header.
for f in "$WIKI"/*.md; do
  [ -e "$f" ] || continue
  head -1 "$f" | grep -Fqx "$HDR" && rm -f -- "$f"
done

emit() {  # emit <src> <dst-basename>
  { echo "$HDR"; echo; cat "$1"; } | sed \
    -e 's|](https://github\.com/sswelm/HumankindAssetFramework#readme)|](Overview)|g' \
    -e 's#](docs/)#](Home)#g' \
    -e "s#](notes/)#]($REPO/tree/master/docs/notes)#g" \
    -e 's#](docs/README\.md#](Home#g' \
    -e 's#](\.\./README\.md#](Overview#g' \
    -e 's#](\.\./CHANGELOG\.md#](Changelog#g' \
    -e 's#](docs/notes/#](#g' \
    -e 's#](docs/#](#g' \
    -e 's#](notes/#](#g' \
    -e 's#](\.\./#](#g' \
    -e 's#](README\.md#](Overview#g' \
    -e 's#](CHANGELOG\.md#](Changelog#g' \
    -e "s#](\(CREDITS\.md\|LICENSE\|llms\.txt\|haf-pack\.example\.json\))#]($REPO/blob/master/\1)#g" \
    -e 's#](\([A-Za-z0-9._-]*\)\.md)#](\1)#g' \
    -e 's#](\([A-Za-z0-9._-]*\)\.md\##](\1\##g' \
    > "$WIKI/$2"
}

emit README.md Overview.md
emit CHANGELOG.md Changelog.md
emit docs/README.md Home.md
n=0
for f in docs/*.md docs/notes/*.md; do
  b="$(basename "$f")"
  [ "$b" = "README.md" ] && continue
  emit "$f" "$b"
  n=$((n + 1))
done
cp tools/wiki-sidebar.md "$WIKI/_Sidebar.md"

# Generated output must not contain empty links, and every simple relative wiki-page target must exist.
fail=0
if grep -nH -F ']()' "$WIKI"/*.md; then
  echo "FAIL: generated wiki contains empty link(s)" >&2
  fail=1
fi
for f in "$WIKI"/*.md; do
  while IFS= read -r target; do
    page="${target%%#*}"
    [ -z "$page" ] && continue
    [ -f "$WIKI/$page.md" ] || {
      echo "FAIL: generated wiki link $f -> $target has no $page.md" >&2
      fail=1
    }
  done < <(grep -oE '\]\([A-Za-z0-9._-]+(#[^)]*)?\)' "$f" | sed -e 's/^](//' -e 's/)$//' || true)
done
[ "$fail" -eq 0 ] || exit 1

echo "Synced README + CHANGELOG + $n doc page(s) + sidebar (incl. $(ls docs/notes/*.md | wc -l) archived note(s)) -> $WIKI"
